In [ ]:
import sqlite3
import pandas as pd

In [ ]:
con = sqlite3.connect('/content/sql-murder-mystery.db')

In [ ]:
print(con)

<sqlite3.Connection object at 0x7dd0e8c24840>

1ST QUERY

In [ ]:
Q1 = '''select* from crime_scene_report where date=20180115 and type='murder' and City ='SQL City'
'''

pd.set_option('display.max_colwidth', None)
pd.read_sql_query(Q1, con)

,date,type,description,city
0,20180115,murder,"Security footage shows that there were 2 witnesses. The first witness lives at the last house on ""Northwestern Dr"". The second witness, named Annabel, lives somewhere on ""Franklin Ave"".",SQL City

2ND QUERY

In [ ]:
Q2 = ''' select * from person where address_street_name='Northwestern Dr' order by address_number desc
'''
pd.read_sql_query(Q2, con)

,id,name,license_id,address_number,address_street_name,ssn
0,14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949
1,17729,Lasonya Wildey,439686,3824,Northwestern Dr,917817122
2,53890,Sophie Tiberio,957671,3755,Northwestern Dr,442830147
3,73368,Torie Thalmann,773862,3697,Northwestern Dr,341559436
4,96595,Coretta Cubie,303645,3631,Northwestern Dr,378403829
5,19420,Cody Schiel,890431,3524,Northwestern Dr,947110049
6,93509,Emmitt Aceuedo,916706,3491,Northwestern Dr,979073160
7,87456,Leonora Wolfsberger,215868,3483,Northwestern Dr,565203106
8,36378,Freddie Ellzey,267882,3449,Northwestern Dr,474117596
9,53076,Boris Bijou,664914,3327,Northwestern Dr,401191868
10,28360,Rashad Cascone,924517,3212,Northwestern Dr,838907424
11,23044,Val Portlock,924989,3143,Northwestern Dr,100593316
12,51114,Christena Saffell,814284,3055,Northwestern Dr,247657547
13,68690,Yer Modest,852404,3046,Northwestern Dr,419238039
14,44004,Alison Eska,327797,2951,Northwestern Dr,306417867
15,98593,Jonah Toner,578982,2947,Northwestern Dr,745853548
16,59307,Cyril Yongue,753524,2903,Northwestern Dr,866057839
17,34155,Allyson Lazenson,814209,2840,Northwestern Dr,991150469
18,90397,Dionna Kranwinkle,797260,2678,Northwestern Dr,278964807
19,54564,Sammie Sengun,217286,2590,Northwestern Dr,848854310
20,53699,Christian Pagano,628433,2585,Northwestern Dr,644772304
21,34352,Vincenza Burkhardt,436470,2512,Northwestern Dr,197913046
22,80921,Donovan Yackley,222395,2386,Northwestern Dr,515049359
23,96178,Galina Khuu,450248,2183,Northwestern Dr,398518185
24,81885,Kurtis Masuda,934201,2108,Northwestern Dr,201272595
25,88423,Teri Ehrich,510876,1879,Northwestern Dr,248637345
26,51552,Bonita Knie,764124,1726,Northwestern Dr,597137908
27,72076,Courtney Bordeaux,324614,1707,Northwestern Dr,347966356
28,81052,Calvin Czelusniak,471483,1516,Northwestern Dr,657531837
29,71924,Laurie Scronce,774116,1418,Northwestern Dr,254883636
30,23960,Kristopher Lagerberg,658777,1392,Northwestern Dr,492912529
31,70485,Andera Kostelecky,354822,1252,Northwestern Dr,787423012
32,22239,Dusty Sigafus,710517,1125,Northwestern Dr,724386723
33,18376,Josh Shi,653712,1091,Northwestern Dr,193899001
34,29608,Willetta Lurvey,800568,1028,Northwestern Dr,843751378
35,33415,Homer Simpson,108392,981,Northwestern Dr,871392019
36,55130,Shiloh Huntoon,472118,951,Northwestern Dr,826647644
37,44542,Ivory Mcgrevey,873842,897,Northwestern Dr,988557407
38,99826,Ivy Kazarian,994470,892,Northwestern Dr,208359813
39,25615,Olevia Morena,388477,812,Northwestern Dr,962831331
40,40760,Renata Faver,976650,745,Northwestern Dr,547572040
41,10010,Muoi Cary,385336,741,Northwestern Dr,828638512
42,39688,Abe Roeker,537445,689,Northwestern Dr,438969447
43,26758,Angelena Billman,942074,629,Northwestern Dr,341854756
44,75484,Del Tacderen,447887,607,Northwestern Dr,243821337
45,12711,Norman Apolito,667757,599,Northwestern Dr,778264744
46,85280,Donn Duin,569122,540,Northwestern Dr,613873810
47,40336,Fredia Billeter,251082,404,Northwestern Dr,108056488
48,15171,Weldon Penso,336999,311,Northwestern Dr,131379495
49,89906,Kinsey Erickson,510019,309,Northwestern Dr,635287661

In [ ]:
Q2_1 = ''' select * from person where name like '%Annabel%' and address_street_name='Franklin Ave'
'''
pd.read_sql_query(Q2_1, con)

,id,name,license_id,address_number,address_street_name,ssn
0,16371,Annabel Miller,490173,103,Franklin Ave,318771143

3RD QUERY

In [ ]:
Q3 = '''select * from interview where person_id = 14887 '''
pd.read_sql_query(Q3, con)

,person_id,transcript
0,14887,"I heard a gunshot and then saw a man run out. He had a ""Get Fit Now Gym"" bag. The membership number on the bag started with ""48Z"". Only gold members have those bags. The man got into a car with a plate that included ""H42W""."

In [ ]:
Q3_1 = '''select * from interview where person_id = 16371 '''
pd.read_sql_query(Q3_1, con)

,person_id,transcript
0,16371,"I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th."

4rth QUERY

In [ ]:
Q4 = ''' select * from get_fit_now_member where id like '48Z%' and membership_status = 'gold' '''
pd.read_sql_query(Q4, con)

      id  person_id           name  membership_start_date membership_status
0  48Z7A      28819   Joe Germuska               20160305              gold
1  48Z55      67318  Jeremy Bowers               20160101              gold

5th QUERY

In [ ]:
Q5 = ''' select * from drivers_license where plate_number like '%H42W%' and gender = 'male' '''
pd.read_sql_query(Q5, con)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,423327,30,70,brown,brown,male,0H42W2,Chevrolet,Spark LS
1,664760,21,71,black,black,male,4H42WR,Nissan,Altima

6th QUERY

In [ ]:
Q6 = '''select* from person where license_id ="423327" OR license_id ="664760" '''
pd.read_sql_query(Q6, con)

,id,name,license_id,address_number,address_street_name,ssn
0,51739,Tushar Chandra,664760,312,Phi St,137882671
1,67318,Jeremy Bowers,423327,530,"Washington Pl, Apt 3A",871539279

7th QUERY

In [ ]:
Q7 = ''' select* from get_fit_now_member where person_id = "51739" or person_id = "67318" '''
pd.read_sql_query(Q7, con)

      id  person_id           name  membership_start_date membership_status
0  48Z55      67318  Jeremy Bowers               20160101              gold

8th QUERY

In [ ]:
Q8 = ''' select * from interview where person_id = 67318 '''
pd.read_sql_query(Q8, con)

,person_id,transcript
0,67318,"I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5"" (65"") or 5'7"" (67""). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.\n"

9th QUERY

In [ ]:
Q9 = ''' select* from drivers_license where hair_color = 'red' and car_make = 'Tesla' and car_model = 'Model S' and gender = 'female' '''
pd.read_sql_query(Q9, con)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,202298,68,66,green,red,female,500123,Tesla,Model S
1,291182,65,66,blue,red,female,08CM64,Tesla,Model S
2,918773,48,65,black,red,female,917UU3,Tesla,Model S

10th QUERY

In [ ]:
Q10 = '''select * from person where license_id = 202298 or  license_id = 291182 or license_id = 918773 '''
pd.read_sql_query(Q10, con)

,id,name,license_id,address_number,address_street_name,ssn
0,78881,Red Korb,918773,107,Camerata Dr,961388910
1,90700,Regina George,291182,332,Maple Ave,337169072
2,99716,Miranda Priestly,202298,1883,Golden Ave,987756388

11th QUERY

In [ ]:
Q11 = '''select person_id, count(1),event_name from facebook_event_checkin group by person_id having count(1) = 3 and date like '%201712%' and event_name = 'SQL Symphony Concert' ;
'''

pd.read_sql_query(Q11, con)

   person_id  count(1)            event_name
0      24556         3  SQL Symphony Concert
1      99716         3  SQL Symphony Concert

12TH QUERY

In [ ]:
Q12 = ''' select * from person where id = 24556 or id = 99716 '''

pd.read_sql_query(Q12, con)

,id,name,license_id,address_number,address_street_name,ssn
0,24556,Bryan Pardo,101191,703,Machine Ln,816663882
1,99716,Miranda Priestly,202298,1883,Golden Ave,987756388

13TH QUERY

In [ ]:
Q13 =''' select * from drivers_license where id = 101191 or id = 202298 AND gender = 'female' '''
pd.read_sql_query(Q13, con)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,202298,68,66,green,red,female,500123,Tesla,Model S

# Miranda Priestly is the Killer.